create extension if not exists pgcrypto;

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text not null unique,
  status text not null default 'offline',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists friends (
  user_id bigint not null references users(id) on delete cascade,
  friend_id bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, friend_id)
);

create table if not exists direct_messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null references users(id) on delete cascade,
  recipient_id bigint not null references users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_by bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists group_members (
  group_id bigint not null references groups(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references groups(id) on delete cascade,
  sender_id bigint not null references users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists calls (
  id bigint generated by default as identity primary key,
  initiator_id bigint not null references users(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  max_participants int not null default 30,
  is_active boolean not null default true
);

create table if not exists call_participants (
  call_id bigint not null references calls(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (call_id, user_id)
);

create table if not exists game_votes (
  id bigint generated by default as identity primary key,
  game_name text not null,
  user_id bigint not null references users(id) on delete cascade,
  voted_at timestamptz not null default now()
);

create or replace view game_vote_counts as
select game_name, count(*)::int as vote_count
from game_votes
group by game_name;
